# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: my-disk-claim
spec:
    resources:
        requests:
            storage: 15Gi
    accessModes:
        - ReadWriteOnce
    storageClassName: slow

---
apiVersion: v1
kind: Pod
metadata:
    name: pv-pod
spec:
    containers:
        - name: test-container
          image: nginx
          volumeMounts:
            - mountPath: /test-pd
              name: test-volume
    volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: my-disk-claim