# ssd-storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: faster
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume1
  labels:
    type: local
spec:
  storageClassName: faster # CHANGE HERE
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim1
spec:
  storageClassName: faster # CHANGE HERE
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi