apiVersion: v1
kind: Pod
metadata:
  name: gce-pd2
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    gcePersistentDisk:
      pdName: pd1
      fsType: ext4